In [1]:
2+2

4

In [8]:
import cv2

img = cv2.imread ("image.png",1)

print (img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [9]:
import cv2

img = cv2.imread ("image.png",0)

print (img)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [12]:
import cv2

img = cv2.imread ("image.png",0)

print (type(img))

<class 'numpy.ndarray'>


In [14]:
import cv2

img = cv2.imread ("image.png",0)

print (img.shape)

(538, 1191)


In [15]:
import cv2

img = cv2.imread ("image.png",1)

print (img.shape)


(538, 1191, 3)


In [4]:
import numpy as np
import cv2

img = cv2.imread ("image.png",0)

cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
#print (img.shape)

In [5]:
import numpy as np
import cv2

img = cv2.imread ("image.png",0)


cv2.imshow('image',img)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [6]:
import numpy as np
import cv2

img = cv2.imread ("image.png",0)

resized = cv2.resize(img, (650,500))

cv2.imshow('image',resized)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [11]:
import numpy as np
import cv2

img = cv2.imread ("image.png",0)

resized = cv2.resize(img, (int(img.shape[1]*2),int(img.shape[0]*2)))

cv2.imshow('image',resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
import cv2
import numpy as np 

#create a cascade classifier object 
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

#reading the file
img = cv2.imread('person.jpg')

#read image as grey scale 
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

#search the coordinates of the image 
faces = face_cascade.detectMultiScale(gray_img, scaleFactor = 1.05, minNeighbors = 5)

print(type(faces))

print(faces)

#create rectangular box
for x,y,w,h in faces:
    img = cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,0), 1)
            # rectanglar( var , first point, last point , color, border )
    
cv2.imshow("gray", img)

cv2.waitKey(0)

cv2.destroyAllWindows()



<class 'numpy.ndarray'>
[[246  59 159 159]]


In [2]:
import cv2
import numpy as np 

#create a cascade classifier object 
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

#reading the file
img = cv2.imread('person.jpg')

#read image as grey scale 
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

#search the coordinates of the image 
faces = face_cascade.detectMultiScale(gray_img, scaleFactor = 1.05, minNeighbors = 5)

print(type(faces))

print(faces)

#create rectangular box
for x,y,w,h in faces:
    img = cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,0), 1)
            # rectanglar( var , first point, last point , color, border )
    
cv2.imshow("gray", img)

cv2.waitKey(0)

cv2.destroyAllWindows()



<class 'numpy.ndarray'>
[[246  59 159 159]]


In [ ]:
import numpy as np 
import cv2,time

video = cv2.VideoCapture(0)

check, frame = video.read()

print(check)
print(frame)

time.sleep(3)

cv2.imshow("Capture Image ",frame)

cv2.waitKey(0)

video.release()

cv2.destroyAllWindows()

True
[[[112 120 137]
  [116 124 141]
  [108 139 130]
  ...
  [166 137 116]
  [165 140 114]
  [166 141 115]]

 [[123 119 133]
  [127 122 136]
  [114 134 129]
  ...
  [159 141 114]
  [151 142 116]
  [152 143 117]]

 [[127 130 120]
  [127 130 120]
  [119 128 127]
  ...
  [159 145 118]
  [147 146 117]
  [146 145 115]]

 ...

 [[ 55  70  95]
  [ 60  74  99]
  [ 39  88  92]
  ...
  [141 117 101]
  [147 135 114]
  [158 147 126]]

 [[ 61  82  81]
  [ 63  84  83]
  [ 41  90  87]
  ...
  [142 119  93]
  [154 132 103]
  [168 146 117]]

 [[ 41  95  63]
  [ 47 101  69]
  [ 43  85  97]
  ...
  [146 120  90]
  [167 123  92]
  [178 134 102]]]


In [1]:
import numpy as np 
import cv2,time

video = cv2.VideoCapture(0)

a = 1 

while True:
    a = a + 1

    check, frame = video.read()
    print(frame)
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    cv2.imshow("Capture Video Bro ",gray)
    
    key = cv2.waitKey(1)
    
    if key == ord('q'):
        break

print(a)

video.release()

cv2.destroyAllWindows()

[[[148 139 127]
  [151 141 129]
  [149 146 135]
  ...
  [187 153 145]
  [172 156 131]
  [171 154 130]]

 [[145 152 126]
  [145 152 126]
  [149 146 135]
  ...
  [181 157 140]
  [183 158 130]
  [180 156 128]]

 [[139 157 129]
  [139 157 129]
  [147 152 137]
  ...
  [181 160 134]
  [180 163 134]
  [181 164 135]]

 ...

 [[117  72  79]
  [123  78  85]
  [ 90  78  80]
  ...
  [180 176 161]
  [183 175 158]
  [181 173 156]]

 [[120  75  87]
  [119  74  86]
  [ 93  78  76]
  ...
  [186 178 159]
  [182 178 156]
  [182 178 156]]

 [[127  71  80]
  [131  76  85]
  [ 91  80  73]
  ...
  [194 176 156]
  [189 170 166]
  [186 167 163]]]
[[[144 156 133]
  [140 152 130]
  [144 138 148]
  ...
  [187 173 127]
  [186 167 134]
  [182 164 130]]

 [[132 151 136]
  [132 151 136]
  [143 146 145]
  ...
  [178 168 131]
  [174 168 133]
  [174 168 133]]

 [[140 149 136]
  [143 152 139]
  [144 150 145]
  ...
  [173 160 137]
  [173 168 130]
  [173 168 130]]

 ...

 [[119  77  72]
  [117  76  71]
  [ 91  61  84]
  ..

[[[140 136 116]
  [138 133 114]
  [119 134 124]
  ...
  [160 154 130]
  [166 156 105]
  [165 155 104]]

 [[124 145 123]
  [122 143 121]
  [135 137 123]
  ...
  [170 154 127]
  [165 162 110]
  [164 161 109]]

 [[135 143 139]
  [131 139 136]
  [135 140 125]
  ...
  [174 155 124]
  [175 154 121]
  [175 154 121]]

 ...

 [[ 83  76  75]
  [ 83  76  75]
  [ 94  71  77]
  ...
  [172 161 147]
  [172 157 148]
  [170 155 146]]

 [[ 78  76  74]
  [ 78  76  74]
  [101  73  75]
  ...
  [170 163 144]
  [177 161 143]
  [176 159 142]]

 [[ 91  84  78]
  [ 98  91  85]
  [111  83  79]
  ...
  [168 169 137]
  [178 169 134]
  [179 170 135]]]
[[[146 136 124]
  [148 139 127]
  [120 145 125]
  ...
  [168 154 120]
  [151 152 122]
  [148 149 119]]

 [[141 139 125]
  [143 141 128]
  [130 147 126]
  ...
  [166 155 120]
  [160 154 123]
  [161 155 124]]

 [[135 137 130]
  [136 139 131]
  [131 139 129]
  ...
  [164 151 128]
  [165 155 124]
  [164 153 123]]

 ...

 [[ 74  58  83]
  [ 75  59  85]
  [ 86  69  72]
  ..

[[[119 142 136]
  [119 142 136]
  [135 139 127]
  ...
  [151 148 123]
  [153 153 112]
  [149 150 109]]

 [[128 145 129]
  [126 143 127]
  [130 143 125]
  ...
  [159 148 127]
  [164 152 115]
  [165 153 116]]

 [[121 152 115]
  [118 148 112]
  [135 136 126]
  ...
  [171 148 127]
  [169 149 125]
  [171 152 128]]

 ...

 [[ 89  86  73]
  [ 88  85  72]
  [106  86  71]
  ...
  [171 161 144]
  [170 162 146]
  [170 162 146]]

 [[ 74  82  53]
  [ 75  83  54]
  [101  87  67]
  ...
  [177 159 146]
  [168 161 149]
  [167 160 148]]

 [[ 63  72  64]
  [ 65  75  66]
  [100  93  53]
  ...
  [185 156 149]
  [168 162 147]
  [167 161 146]]]
[[[146 134 120]
  [150 139 125]
  [132 125 144]
  ...
  [180 145 121]
  [164 159 119]
  [163 158 118]]

 [[157 127 127]
  [160 130 131]
  [133 128 142]
  ...
  [181 151 126]
  [168 159 119]
  [170 161 121]]

 [[140 136 135]
  [140 136 135]
  [132 133 135]
  ...
  [176 155 122]
  [180 154 124]
  [178 151 122]]

 ...

 [[ 81  97  51]
  [ 78  93  48]
  [ 98  85  69]
  ..

[[[122 132 130]
  [123 133 132]
  [138 131 130]
  ...
  [165 153 116]
  [166 142 132]
  [166 142 132]]

 [[131 133 133]
  [132 134 134]
  [134 135 131]
  ...
  [167 151 118]
  [162 143 132]
  [162 143 132]]

 [[130 141 137]
  [128 139 135]
  [127 137 133]
  ...
  [169 148 124]
  [163 147 127]
  [165 149 128]]

 ...

 [[ 82  67  51]
  [ 87  72  56]
  [ 94  98  79]
  ...
  [122  92  74]
  [113  95  66]
  [112  94  65]]

 [[ 93  60  49]
  [ 96  63  53]
  [ 83  82  73]
  ...
  [134  91  70]
  [113  99  58]
  [110  97  56]]

 [[103  63  47]
  [104  64  48]
  [ 70  58  74]
  ...
  [148  98  58]
  [101 114  50]
  [ 99 111  48]]]
[[[133 134 130]
  [135 137 132]
  [114 148 122]
  ...
  [169 150 124]
  [153 154 118]
  [147 148 112]]

 [[135 132 133]
  [137 135 135]
  [126 144 125]
  ...
  [169 148 124]
  [157 153 118]
  [154 150 114]]

 [[147 129 143]
  [148 130 144]
  [132 139 133]
  ...
  [162 149 121]
  [165 151 119]
  [169 155 123]]

 ...

 [[ 86  62  72]
  [ 95  71  82]
  [102 108  91]
  ..

[[[128 148 156]
  [129 149 157]
  [140 158 150]
  ...
  [183 160 141]
  [165 166 148]
  [166 168 149]]

 [[142 157 152]
  [142 157 152]
  [138 157 149]
  ...
  [181 161 144]
  [177 165 146]
  [177 165 146]]

 [[151 161 144]
  [148 159 141]
  [139 157 145]
  ...
  [181 164 146]
  [177 166 143]
  [177 166 143]]

 ...

 [[118  86  66]
  [118  86  66]
  [109  77  76]
  ...
  [144 117  89]
  [143 113  93]
  [148 118  98]]

 [[107  97  92]
  [103  94  88]
  [106  76  72]
  ...
  [143 115  90]
  [139 114  93]
  [141 116  95]]

 [[113 108  95]
  [111 106  93]
  [120  89  80]
  ...
  [137 117  88]
  [122 118  87]
  [120 117  86]]]
[[[156 157 147]
  [153 154 145]
  [147 148 143]
  ...
  [178 158 156]
  [179 166 143]
  [175 163 140]]

 [[150 150 150]
  [150 150 150]
  [147 153 143]
  ...
  [178 160 151]
  [181 166 143]
  [180 165 142]]

 [[137 162 148]
  [135 160 147]
  [146 158 145]
  ...
  [175 165 146]
  [182 168 141]
  [183 170 142]]

 ...

 [[119  82  70]
  [121  84  72]
  [109  88  78]
  ..

[[[144 154 152]
  [144 154 152]
  [139 154 151]
  ...
  [162 162 150]
  [165 163 143]
  [165 163 143]]

 [[152 152 152]
  [151 151 151]
  [143 153 151]
  ...
  [166 162 151]
  [168 164 144]
  [168 164 144]]

 [[151 149 149]
  [151 149 149]
  [147 154 148]
  ...
  [169 165 149]
  [170 164 147]
  [171 165 148]]

 ...

 [[ 94  61  89]
  [ 91  59  87]
  [ 77  62  87]
  ...
  [122  93  70]
  [114  99  70]
  [120 105  75]]

 [[101  60  81]
  [ 98  57  77]
  [ 89  57  85]
  ...
  [118  96  67]
  [123  92  69]
  [126  95  73]]

 [[ 97  63  76]
  [ 94  60  72]
  [101  59  82]
  ...
  [116 104  58]
  [135  88  64]
  [137  90  66]]]
[[[144 151 143]
  [144 151 143]
  [159 150 143]
  ...
  [174 158 156]
  [168 165 154]
  [168 165 154]]

 [[157 155 142]
  [156 154 141]
  [153 152 141]
  ...
  [167 161 157]
  [169 167 153]
  [173 170 157]]

 [[146 158 145]
  [145 157 143]
  [149 157 142]
  ...
  [164 165 155]
  [169 171 153]
  [172 173 155]]

 ...

 [[ 82 103  95]
  [ 82 103  95]
  [ 96  99 103]
  ..

[[[140 160 143]
  [140 160 143]
  [145 154 148]
  ...
  [179 165 145]
  [175 170 145]
  [173 167 143]]

 [[150 158 146]
  [150 158 146]
  [148 157 149]
  ...
  [181 165 145]
  [179 169 145]
  [177 166 143]]

 [[156 159 150]
  [155 158 148]
  [150 158 146]
  ...
  [178 168 144]
  [179 171 141]
  [180 172 142]]

 ...

 [[121 123 125]
  [123 124 126]
  [121 127 121]
  ...
  [132 107  79]
  [132  99  82]
  [127  95  77]]

 [[125 128 118]
  [125 128 118]
  [120 123 121]
  ...
  [124 105  81]
  [120 100  85]
  [120 100  85]]

 [[123 123 125]
  [123 123 125]
  [119 120 116]
  ...
  [123 102  85]
  [111 101  89]
  [116 106  94]]]
[[[129 161 140]
  [128 160 139]
  [132 146 157]
  ...
  [189 165 141]
  [171 172 133]
  [170 171 132]]

 [[146 161 142]
  [144 160 141]
  [139 149 154]
  ...
  [187 166 140]
  [184 171 135]
  [184 171 135]]

 [[148 147 149]
  [149 148 151]
  [142 150 146]
  ...
  [183 170 142]
  [183 170 141]
  [182 169 139]]

 ...

 [[104  86  91]
  [103  85  90]
  [100  85  94]
  ..

[[[149 154 139]
  [154 159 144]
  [156 164 149]
  ...
  [169 169 141]
  [173 164 157]
  [172 163 155]]

 [[153 154 138]
  [157 157 141]
  [153 163 148]
  ...
  [164 164 144]
  [169 162 154]
  [168 161 153]]

 [[154 155 139]
  [154 155 139]
  [151 160 145]
  ...
  [159 160 144]
  [165 159 142]
  [166 161 143]]

 ...

 [[ 91  88  68]
  [ 87  85  65]
  [ 76  85  57]
  ...
  [112  89  63]
  [116  85  62]
  [117  86  63]]

 [[107  96  62]
  [103  92  57]
  [ 80  83  60]
  ...
  [108  88  66]
  [115  89  66]
  [113  87  63]]

 [[117  88  59]
  [115  86  56]
  [ 82  89  56]
  ...
  [103  90  69]
  [118  87  85]
  [111  80  78]]]
[[[162 162 142]
  [164 164 144]
  [155 166 148]
  ...
  [123 144 141]
  [126 148 136]
  [124 146 133]]

 [[159 162 139]
  [161 164 141]
  [156 164 147]
  ...
  [132 145 140]
  [133 148 137]
  [133 148 137]]

 [[155 163 139]
  [155 163 139]
  [157 164 144]
  ...
  [136 149 138]
  [130 149 141]
  [131 150 142]]

 ...

 [[ 56  82  78]
  [ 58  85  80]
  [ 65  88  66]
  ..

[[[146 147 149]
  [146 147 149]
  [150 147 148]
  ...
  [167 167 146]
  [167 167 146]
  [166 166 145]]

 [[140 149 148]
  [141 151 149]
  [150 148 146]
  ...
  [179 165 145]
  [175 167 143]
  [174 166 142]]

 [[146 151 143]
  [147 152 144]
  [149 151 144]
  ...
  [183 167 140]
  [180 169 141]
  [180 169 141]]

 ...

 [[ 95 116 113]
  [ 95 116 113]
  [ 84 116 109]
  ...
  [121 101  66]
  [127  99  68]
  [126  98  66]]

 [[ 92 120  99]
  [ 95 122 102]
  [ 92 118 107]
  ...
  [119 101  68]
  [124  97  70]
  [125  98  71]]

 [[ 96 116  83]
  [ 98 118  85]
  [107 118  93]
  ...
  [120  96  73]
  [116  96  67]
  [119  99  71]]]
[[[146 147 149]
  [147 149 151]
  [147 159 139]
  ...
  [170 162 147]
  [171 162 143]
  [170 161 142]]

 [[162 148 150]
  [162 148 150]
  [145 155 139]
  ...
  [173 165 148]
  [179 166 143]
  [179 166 143]]

 [[152 150 150]
  [152 150 150]
  [145 151 146]
  ...
  [172 169 144]
  [178 168 143]
  [180 171 145]]

 ...

 [[ 95 112 109]
  [ 96 113 111]
  [ 86 116 109]
  ..

[[[140 153 149]
  [141 154 150]
  [150 153 145]
  ...
  [181 170 142]
  [177 172 148]
  [173 167 143]]

 [[150 153 145]
  [150 153 145]
  [146 153 147]
  ...
  [180 169 141]
  [176 166 147]
  [174 164 145]]

 [[149 153 141]
  [148 152 140]
  [139 153 146]
  ...
  [178 170 139]
  [175 166 145]
  [171 163 141]]

 ...

 [[ 59 105 109]
  [ 60 107 110]
  [ 81 107 110]
  ...
  [171 155 140]
  [166 155 146]
  [167 157 147]]

 [[ 79 108 104]
  [ 81 109 105]
  [ 80 109 111]
  ...
  [167 154 140]
  [161 155 145]
  [161 155 145]]

 [[103 111 109]
  [102 109 108]
  [ 82 113 110]
  ...
  [169 150 147]
  [161 159 132]
  [164 161 134]]]
[[[142 143 148]
  [147 148 152]
  [151 155 143]
  ...
  [175 169 138]
  [191 166 138]
  [186 161 134]]

 [[140 149 148]
  [143 153 151]
  [147 155 145]
  ...
  [178 170 139]
  [181 168 138]
  [178 166 136]]

 [[146 154 152]
  [144 151 150]
  [144 151 150]
  ...
  [179 168 140]
  [177 167 141]
  [177 167 141]]

 ...

 [[ 62 103 117]
  [ 63 104 118]
  [ 62 111 110]
  ..

[[[144 149 148]
  [145 150 149]
  [146 151 141]
  ...
  [171 169 140]
  [171 175 143]
  [166 170 137]]

 [[148 147 149]
  [148 147 149]
  [146 150 145]
  ...
  [178 169 141]
  [176 172 143]
  [176 172 143]]

 [[143 151 155]
  [142 150 153]
  [143 150 149]
  ...
  [180 168 143]
  [176 172 143]
  [179 175 146]]

 ...

 [[ 63  99 120]
  [ 64 100 122]
  [ 70 111 105]
  ...
  [172 171 160]
  [166 171 158]
  [168 172 160]]

 [[ 85 107  96]
  [ 86 108  98]
  [ 79 108 108]
  ...
  [172 170 161]
  [169 167 160]
  [169 167 160]]

 [[ 65 113  99]
  [ 68 116 101]
  [ 90 106 112]
  ...
  [174 171 160]
  [168 172 155]
  [168 172 155]]]
[[[150 144 154]
  [152 147 157]
  [136 149 151]
  ...
  [179 166 143]
  [176 171 138]
  [178 174 140]]

 [[146 151 150]
  [147 152 151]
  [143 150 149]
  ...
  [178 168 143]
  [179 172 139]
  [180 173 140]]

 [[141 161 135]
  [139 159 133]
  [145 151 147]
  ...
  [179 170 144]
  [182 168 141]
  [181 167 140]]

 ...

 [[ 80 108 112]
  [ 79 107 111]
  [ 74 110 111]
  ..

[[[133 142 141]
  [137 147 145]
  [140 156 135]
  ...
  [174 164 152]
  [192 167 148]
  [188 162 144]]

 [[139 149 141]
  [141 150 142]
  [144 153 138]
  ...
  [177 164 148]
  [178 166 147]
  [177 165 146]]

 [[137 158 143]
  [135 156 141]
  [141 153 144]
  ...
  [177 165 146]
  [177 165 146]
  [178 166 147]]

 ...

 [[ 66 105 123]
  [ 67 106 125]
  [ 75 115 111]
  ...
  [142 131 110]
  [136 133 108]
  [136 133 108]]

 [[ 66 106 118]
  [ 69 108 120]
  [ 73 116 109]
  ...
  [138 131 111]
  [137 131 107]
  [133 128 103]]

 [[ 55 109 103]
  [ 58 113 106]
  [ 69 113 110]
  ...
  [132 127 121]
  [140 130 111]
  [140 130 111]]]
[[[147 152 135]
  [149 155 138]
  [139 154 150]
  ...
  [183 167 147]
  [185 163 146]
  [185 163 146]]

 [[139 153 137]
  [140 154 138]
  [146 153 147]
  ...
  [183 164 145]
  [179 165 145]
  [179 165 145]]

 [[155 155 142]
  [154 154 141]
  [149 155 145]
  ...
  [183 165 143]
  [179 165 145]
  [180 166 146]]

 ...

 [[ 90 105 114]
  [ 89 104 113]
  [ 76 110 109]
  ..

[[[119 154 151]
  [121 156 153]
  [136 151 153]
  ...
  [168 167 142]
  [178 168 144]
  [177 166 143]]

 [[153 158 150]
  [152 156 149]
  [137 154 151]
  ...
  [175 167 143]
  [176 168 144]
  [177 169 145]]

 [[150 153 145]
  [150 153 145]
  [140 153 149]
  ...
  [175 165 146]
  [174 168 144]
  [175 170 145]]

 ...

 [[ 64 108 119]
  [ 64 108 119]
  [ 84 111 111]
  ...
  [148 117 115]
  [139 121 108]
  [135 117 104]]

 [[ 60 115 106]
  [ 60 115 106]
  [ 66 116 108]
  ...
  [139 121 106]
  [134 123 102]
  [133 121 100]]

 [[ 60 110 104]
  [ 60 110 104]
  [ 39 119 106]
  ...
  [125 128 105]
  [130 125  98]
  [131 126 100]]]
[[[132 153 143]
  [131 152 142]
  [148 154 135]
  ...
  [175 174 137]
  [175 167 143]
  [172 165 141]]

 [[140 153 141]
  [140 153 141]
  [144 154 137]
  ...
  [176 172 136]
  [176 169 143]
  [175 168 141]]

 [[145 152 144]
  [145 152 144]
  [140 153 141]
  ...
  [177 172 139]
  [175 171 142]
  [176 172 143]]

 ...

 [[ 63 127  93]
  [ 62 125  92]
  [ 80 116  96]
  ..

[[[126 155 141]
  [126 155 141]
  [148 148 148]
  ...
  [188 170 136]
  [178 159 153]
  [181 163 157]]

 [[146 155 142]
  [145 154 141]
  [149 150 147]
  ...
  [180 170 139]
  [182 164 149]
  [184 167 151]]

 [[152 150 150]
  [152 150 150]
  [147 150 147]
  ...
  [179 170 144]
  [181 170 142]
  [181 170 142]]

 ...

 [[ 75 119 112]
  [ 74 118 111]
  [ 82 114 107]
  ...
  [174 171 158]
  [175 168 160]
  [175 168 160]]

 [[ 52 122 102]
  [ 53 124 103]
  [ 78 118 107]
  ...
  [178 171 158]
  [176 170 160]
  [176 170 160]]

 [[ 53  98 114]
  [ 57 102 117]
  [ 78 118 109]
  ...
  [182 171 155]
  [175 172 161]
  [174 171 160]]]
[[[139 162 135]
  [136 158 132]
  [126 157 145]
  ...
  [186 168 141]
  [183 165 143]
  [183 165 143]]

 [[150 152 140]
  [149 150 139]
  [144 155 144]
  ...
  [183 165 143]
  [183 165 143]
  [183 165 143]]

 [[156 148 145]
  [156 148 145]
  [147 155 145]
  ...
  [182 165 147]
  [184 167 143]
  [184 167 143]]

 ...

 [[ 75 111 112]
  [ 75 111 112]
  [ 88 112 108]
  ..

[[[131 152 142]
  [134 156 145]
  [141 148 154]
  ...
  [163 170 141]
  [176 165 138]
  [178 167 139]]

 [[150 152 140]
  [152 154 142]
  [139 150 151]
  ...
  [172 169 144]
  [177 168 140]
  [176 167 139]]

 [[150 159 141]
  [149 157 140]
  [138 154 147]
  ...
  [177 166 145]
  [179 167 141]
  [179 167 141]]

 ...

 [[ 76 117 103]
  [ 74 115 101]
  [ 86 110 106]
  ...
  [177 167 162]
  [174 171 160]
  [175 172 161]]

 [[ 77 123  95]
  [ 77 123  95]
  [ 81 115 102]
  ...
  [173 169 160]
  [174 172 156]
  [175 173 158]]

 [[ 64 125  92]
  [ 65 126  93]
  [ 76 120 106]
  ...
  [167 170 156]
  [178 171 156]
  [180 174 159]]]
[[[131 155 151]
  [131 155 151]
  [136 154 149]
  ...
  [179 173 137]
  [183 164 145]
  [183 164 145]]

 [[144 147 151]
  [144 147 151]
  [135 152 149]
  ...
  [182 173 140]
  [187 167 145]
  [187 167 145]]

 [[145 145 151]
  [146 146 153]
  [140 149 148]
  ...
  [183 167 147]
  [181 169 144]
  [181 169 144]]

 ...

 [[ 88 107 111]
  [ 88 107 111]
  [ 84 110 106]
  ..

[[[137 147 150]
  [138 148 151]
  [142 147 153]
  ...
  [200 169 140]
  [179 170 144]
  [174 165 139]]

 [[140 149 148]
  [141 151 149]
  [145 149 151]
  ...
  [185 174 141]
  [173 172 142]
  [170 168 139]]

 [[133 162 144]
  [131 160 142]
  [147 150 147]
  ...
  [180 172 142]
  [175 171 142]
  [174 170 141]]

 ...

 [[ 57 112 117]
  [ 60 115 120]
  [ 84 115 112]
  ...
  [177 167 162]
  [175 167 163]
  [176 168 164]]

 [[ 56 121 111]
  [ 56 121 111]
  [ 85 113 111]
  ...
  [179 167 160]
  [168 170 163]
  [168 170 163]]

 [[ 53 119 104]
  [ 53 119 104]
  [ 84 112 103]
  ...
  [180 174 157]
  [159 174 162]
  [156 172 160]]]
[[[142 150 153]
  [142 150 153]
  [148 148 148]
  ...
  [180 163 152]
  [183 167 147]
  [177 161 141]]

 [[133 152 149]
  [134 153 150]
  [145 151 147]
  ...
  [182 164 151]
  [178 165 149]
  [176 163 147]]

 [[123 160 138]
  [124 161 139]
  [148 151 149]
  ...
  [178 167 146]
  [172 166 151]
  [173 167 152]]

 ...

 [[ 58 113 106]
  [ 61 115 109]
  [ 81 112 107]
  ..

[[[143 156 138]
  [142 155 137]
  [142 151 145]
  ...
  [170 163 144]
  [170 161 142]
  [175 165 146]]

 [[147 149 142]
  [147 149 142]
  [148 149 145]
  ...
  [176 164 144]
  [182 163 144]
  [184 166 146]]

 [[131 153 147]
  [131 153 147]
  [149 151 144]
  ...
  [179 165 145]
  [184 167 143]
  [185 168 144]]

 ...

 [[ 92 117 104]
  [ 90 115 102]
  [ 94 113 105]
  ...
  [178 170 160]
  [173 169 158]
  [174 171 160]]

 [[ 90 112 108]
  [ 90 112 108]
  [ 85 114 109]
  ...
  [177 168 160]
  [170 172 158]
  [170 172 158]]

 [[ 57 110 108]
  [ 60 112 111]
  [ 72 111 116]
  ...
  [178 168 163]
  [165 169 159]
  [164 167 158]]]
[[[124 154 145]
  [129 160 150]
  [140 162 138]
  ...
  [181 165 145]
  [179 171 141]
  [174 167 136]]

 [[140 149 148]
  [141 151 149]
  [144 153 140]
  ...
  [182 168 141]
  [177 172 141]
  [175 169 138]]

 [[149 148 151]
  [148 147 149]
  [145 146 148]
  ...
  [180 169 141]
  [174 169 143]
  [173 168 141]]

 ...

 [[ 59 119 109]
  [ 58 118 108]
  [ 80 114 108]
  ..

[[[159 153 149]
  [160 154 150]
  [150 157 156]
  ...
  [180 177 152]
  [194 165 163]
  [194 165 163]]

 [[155 156 152]
  [155 156 152]
  [151 159 156]
  ...
  [183 175 151]
  [192 167 160]
  [192 167 160]]

 [[155 163 159]
  [152 160 157]
  [152 161 155]
  ...
  [189 175 150]
  [193 173 151]
  [195 175 154]]

 ...

 [[ 85 119 120]
  [ 85 119 120]
  [ 89 124 107]
  ...
  [187 176 167]
  [180 175 164]
  [180 175 164]]

 [[ 96 118 101]
  [ 99 121 103]
  [ 86 125 112]
  ...
  [186 174 163]
  [179 173 165]
  [178 172 164]]

 [[103 113 105]
  [106 115 107]
  [ 76 127 119]
  ...
  [189 170 159]
  [176 170 167]
  [177 172 168]]]
[[[139 157 165]
  [138 155 164]
  [155 155 155]
  ...
  [176 177 147]
  [182 174 157]
  [180 172 155]]

 [[149 156 162]
  [148 155 161]
  [155 155 155]
  ...
  [183 177 148]
  [194 172 157]
  [195 173 158]]

 [[157 160 159]
  [155 158 157]
  [155 155 155]
  ...
  [190 176 151]
  [193 176 154]
  [194 177 155]]

 ...

 [[ 84 121 120]
  [ 83 120 118]
  [ 90 120 111]
  ..

[[[133 158 156]
  [135 161 159]
  [159 158 147]
  ...
  [200 166 158]
  [194 170 153]
  [193 169 152]]

 [[145 157 155]
  [145 157 155]
  [158 159 150]
  ...
  [194 168 156]
  [191 173 151]
  [191 173 151]]

 [[160 158 150]
  [160 158 150]
  [156 157 154]
  ...
  [193 177 152]
  [192 181 147]
  [192 181 147]]

 ...

 [[ 59 118 113]
  [ 65 123 118]
  [ 91 122 110]
  ...
  [177 176 167]
  [180 174 166]
  [180 174 166]]

 [[ 81 125 109]
  [ 82 126 110]
  [ 84 129 112]
  ...
  [184 174 169]
  [186 171 169]
  [186 171 169]]

 [[ 82 122 118]
  [ 84 125 120]
  [ 75 128 120]
  ...
  [194 170 172]
  [188 170 171]
  [191 172 173]]]
[[[133 159 150]
  [135 160 152]
  [147 165 146]
  ...
  [193 175 155]
  [174 177 147]
  [176 179 149]]

 [[144 154 152]
  [144 154 152]
  [152 161 148]
  ...
  [187 172 156]
  [184 174 148]
  [184 174 148]]

 [[152 158 154]
  [151 156 153]
  [154 158 153]
  ...
  [185 174 153]
  [192 171 152]
  [192 171 152]]

 ...

 [[ 69 127 109]
  [ 69 127 109]
  [ 85 122 114]
  ..

[[[165 150 152]
  [166 151 154]
  [154 156 149]
  ...
  [185 175 151]
  [198 174 144]
  [204 180 149]]

 [[153 157 152]
  [153 157 152]
  [155 158 148]
  ...
  [185 175 150]
  [184 176 145]
  [186 178 148]]

 [[147 169 149]
  [144 167 147]
  [156 159 150]
  ...
  [191 174 150]
  [185 177 146]
  [186 178 148]]

 ...

 [[ 85 122 107]
  [ 87 124 109]
  [ 91 124 107]
  ...
  [186 176 171]
  [179 175 169]
  [178 174 167]]

 [[ 86 118 117]
  [ 87 119 118]
  [ 82 127 108]
  ...
  [179 176 170]
  [177 175 169]
  [177 175 169]]

 [[ 70 114 120]
  [ 74 117 124]
  [ 65 129 114]
  ...
  [169 178 170]
  [178 171 172]
  [178 171 172]]]
[[[148 152 156]
  [147 150 155]
  [152 152 152]
  ...
  [193 175 146]
  [197 165 158]
  [197 165 158]]

 [[155 155 155]
  [154 154 154]
  [153 155 155]
  ...
  [192 174 145]
  [192 168 158]
  [192 168 158]]

 [[160 165 157]
  [157 162 155]
  [150 157 156]
  ...
  [192 171 152]
  [190 171 153]
  [190 171 153]]

 ...

 [[ 83 112 107]
  [ 86 115 111]
  [ 93 118 111]
  ..

[[[165 154 153]
  [168 157 157]
  [144 165 159]
  ...
  [188 173 148]
  [189 171 156]
  [188 170 155]]

 [[165 154 153]
  [167 156 156]
  [149 159 157]
  ...
  [196 172 148]
  [186 174 156]
  [185 173 154]]

 [[164 155 154]
  [164 155 154]
  [157 159 154]
  ...
  [196 169 155]
  [191 172 154]
  [191 172 154]]

 ...

 [[ 72 108 111]
  [ 74 109 112]
  [ 83 111 102]
  ...
  [184 173 166]
  [182 174 164]
  [181 173 163]]

 [[ 87 107 104]
  [ 90 109 106]
  [ 78 115 100]
  ...
  [182 174 164]
  [177 178 164]
  [176 176 163]]

 [[ 87 113 102]
  [ 88 115 103]
  [ 80 117  95]
  ...
  [182 174 164]
  [175 179 165]
  [173 178 164]]]
[[[150 156 159]
  [149 154 158]
  [153 143 159]
  ...
  [190 179 156]
  [192 176 156]
  [191 175 155]]

 [[150 157 156]
  [150 157 156]
  [154 152 157]
  ...
  [190 178 155]
  [186 178 156]
  [184 175 154]]

 [[155 158 148]
  [155 158 148]
  [154 158 153]
  ...
  [195 177 150]
  [188 179 153]
  [188 179 153]]

 ...

 [[ 79 115 109]
  [ 83 119 113]
  [ 91 122 110]
  ..

[[[152 152 152]
  [155 155 155]
  [155 154 156]
  ...
  [179 176 151]
  [196 167 151]
  [197 168 152]]

 [[163 156 157]
  [162 155 156]
  [155 155 155]
  ...
  [180 175 148]
  [193 169 150]
  [193 169 150]]

 [[159 159 164]
  [155 156 160]
  [156 157 154]
  ...
  [187 176 148]
  [188 174 147]
  [188 174 147]]

 ...

 [[ 72 125 116]
  [ 71 124 115]
  [ 86 120 114]
  ...
  [183 181 166]
  [179 178 167]
  [176 176 164]]

 [[ 74 122 114]
  [ 71 120 112]
  [ 86 117 112]
  ...
  [181 179 163]
  [180 180 166]
  [177 178 164]]

 [[ 87 107 122]
  [ 85 105 120]
  [ 80 110 123]
  ...
  [184 177 158]
  [181 176 170]
  [178 174 167]]]
[[[152 158 153]
  [151 157 152]
  [150 152 158]
  ...
  [200 170 150]
  [183 179 143]
  [186 183 147]]

 [[146 164 152]
  [144 162 150]
  [150 152 158]
  ...
  [191 173 151]
  [191 180 146]
  [195 184 149]]

 [[155 166 153]
  [151 162 149]
  [149 156 155]
  ...
  [192 174 154]
  [191 177 152]
  [194 179 154]]

 ...

 [[ 95 121 112]
  [ 95 121 112]
  [ 89 124 109]
  ..

[[[159 146 151]
  [164 151 155]
  [159 164 154]
  ...
  [189 175 150]
  [196 169 153]
  [196 169 153]]

 [[152 148 153]
  [156 152 157]
  [157 162 155]
  ...
  [186 174 148]
  [186 171 153]
  [186 171 153]]

 [[158 158 158]
  [158 158 158]
  [157 157 157]
  ...
  [183 177 148]
  [185 175 151]
  [185 175 151]]

 ...

 [[ 86 106 121]
  [ 88 108 123]
  [ 92 118 114]
  ...
  [185 178 163]
  [181 177 167]
  [181 177 167]]

 [[ 84 111 113]
  [ 86 113 115]
  [ 91 122 112]
  ...
  [180 175 164]
  [179 176 167]
  [179 176 167]]

 [[ 69 117 118]
  [ 69 117 118]
  [ 95 127 112]
  ...
  [176 178 160]
  [180 176 163]
  [180 176 163]]]
[[[167 153 153]
  [167 153 153]
  [152 154 149]
  ...
  [186 174 156]
  [193 174 157]
  [191 172 154]]

 [[161 162 155]
  [159 159 152]
  [153 158 150]
  ...
  [188 174 156]
  [191 175 155]
  [190 174 154]]

 [[159 163 156]
  [154 159 151]
  [152 158 153]
  ...
  [188 175 154]
  [191 177 152]
  [192 178 153]]

 ...

 [[ 86 106 132]
  [ 88 109 135]
  [ 95 119 115]
  ..

[[[142 159 143]
  [146 163 146]
  [161 161 161]
  ...
  [182 175 148]
  [184 174 157]
  [182 171 155]]

 [[156 162 145]
  [158 164 147]
  [157 161 158]
  ...
  [191 175 148]
  [183 177 155]
  [183 177 155]]

 [[161 157 156]
  [160 156 154]
  [159 158 154]
  ...
  [194 176 149]
  [183 179 150]
  [182 178 149]]

 ...

 [[ 90 115 122]
  [ 91 116 123]
  [ 89 120 115]
  ...
  [184 173 166]
  [182 176 165]
  [185 179 169]]

 [[ 86 114 125]
  [ 85 113 124]
  [ 83 121 115]
  ...
  [178 174 166]
  [180 173 167]
  [180 173 167]]

 [[ 74 114 119]
  [ 74 114 119]
  [ 71 124 108]
  ...
  [172 175 167]
  [184 172 167]
  [183 171 166]]]
[[[157 153 151]
  [159 155 153]
  [170 156 151]
  ...
  [193 168 154]
  [199 172 144]
  [200 173 145]]

 [[153 155 155]
  [154 156 156]
  [157 156 152]
  ...
  [196 169 153]
  [192 173 147]
  [192 173 147]]

 [[149 161 161]
  [148 159 160]
  [154 159 151]
  ...
  [194 174 152]
  [187 173 154]
  [188 174 156]]

 ...

 [[ 88 112 120]
  [ 91 116 123]
  [ 94 123 112]
  ..

[[[155 168 145]
  [154 166 144]
  [150 164 142]
  ...
  [180 174 150]
  [194 172 148]
  [197 176 152]]

 [[161 168 146]
  [159 167 145]
  [152 167 144]
  ...
  [192 172 150]
  [188 177 149]
  [189 178 150]]

 [[154 162 154]
  [154 162 154]
  [155 164 151]
  ...
  [194 176 149]
  [191 178 150]
  [192 179 152]]

 ...

 [[ 77 120 109]
  [ 80 122 111]
  [ 87 122 114]
  ...
  [145 131 120]
  [145 130 121]
  [145 130 121]]

 [[ 71 124 115]
  [ 71 124 115]
  [ 81 129 110]
  ...
  [140 132 122]
  [143 127 120]
  [141 125 118]]

 [[ 61 127 112]
  [ 65 132 117]
  [ 82 133 109]
  ...
  [130 131 129]
  [140 128 116]
  [140 128 116]]]
[[[159 153 156]
  [159 153 156]
  [141 157 156]
  ...
  [186 171 155]
  [197 172 151]
  [198 173 152]]

 [[141 156 158]
  [142 157 159]
  [143 160 157]
  ...
  [193 171 154]
  [192 179 152]
  [192 179 152]]

 [[145 162 159]
  [144 161 158]
  [144 161 158]
  ...
  [190 174 154]
  [189 178 150]
  [192 180 153]]

 ...

 [[ 85 120 117]
  [ 85 120 117]
  [ 89 123 110]
  ..

[[[149 168 147]
  [151 169 148]
  [161 161 148]
  ...
  [184 173 150]
  [182 168 161]
  [181 167 160]]

 [[155 168 145]
  [155 168 145]
  [156 160 148]
  ...
  [182 174 150]
  [180 169 160]
  [180 169 160]]

 [[157 168 136]
  [155 165 134]
  [153 158 150]
  ...
  [182 176 154]
  [181 172 158]
  [181 172 158]]

 ...

 [[ 85 115 119]
  [ 86 116 120]
  [ 94 120 111]
  ...
  [141 104  92]
  [142 106  92]
  [142 106  92]]

 [[ 89 122 112]
  [ 89 122 112]
  [ 87 122 112]
  ...
  [140 106  93]
  [144 104  95]
  [145 105  96]]

 [[ 79 126 107]
  [ 80 128 108]
  [ 82 131 109]
  ...
  [147 105  96]
  [146 101 101]
  [149 103 103]]]
[[[149 161 161]
  [142 154 154]
  [134 150 164]
  ...
  [196 169 155]
  [195 167 155]
  [196 168 156]]

 [[150 160 158]
  [147 156 155]
  [145 154 160]
  ...
  [188 171 153]
  [188 171 153]
  [189 172 154]]

 [[145 164 149]
  [145 164 149]
  [144 161 158]
  ...
  [185 173 154]
  [186 175 154]
  [185 174 153]]

 ...

 [[ 91 122 103]
  [ 90 121 102]
  [ 92 115 109]
  ..

[[[154 153 155]
  [151 151 153]
  [152 149 159]
  ...
  [177 179 146]
  [185 169 155]
  [183 167 154]]

 [[154 154 154]
  [152 152 152]
  [151 154 158]
  ...
  [188 177 149]
  [197 171 154]
  [196 169 153]]

 [[153 166 153]
  [150 164 150]
  [149 160 156]
  ...
  [192 175 152]
  [198 173 152]
  [197 172 151]]

 ...

 [[ 73 121 109]
  [ 73 121 109]
  [ 89 122 105]
  ...
  [162 163 160]
  [168 163 157]
  [169 164 158]]

 [[ 70 126 108]
  [ 69 125 107]
  [ 89 124 107]
  ...
  [160 164 159]
  [167 165 157]
  [168 167 158]]

 [[ 65 120 113]
  [ 63 118 111]
  [ 91 125 106]
  ...
  [157 167 158]
  [162 164 157]
  [161 163 156]]]
[[[141 154 161]
  [143 157 164]
  [146 155 161]
  ...
  [196 174 145]
  [181 172 150]
  [182 173 152]]

 [[135 156 160]
  [137 159 162]
  [148 156 159]
  ...
  [192 173 147]
  [188 173 150]
  [188 173 150]]

 [[151 150 155]
  [155 153 158]
  [150 157 156]
  ...
  [193 173 151]
  [191 173 151]
  [193 176 154]]

 ...

 [[ 50 118 127]
  [ 50 118 127]
  [ 86 118 109]
  ..

[[[145 159 150]
  [146 160 151]
  [161 163 144]
  ...
  [187 172 156]
  [183 171 159]
  [182 170 158]]

 [[153 162 149]
  [153 162 149]
  [158 160 146]
  ...
  [190 170 155]
  [187 171 158]
  [188 172 159]]

 [[157 165 150]
  [156 164 149]
  [156 157 154]
  ...
  [189 171 156]
  [190 173 156]
  [191 175 157]]

 ...

 [[ 84 104 133]
  [ 87 107 135]
  [ 96 112 117]
  ...
  [186 173 170]
  [186 174 164]
  [188 175 165]]

 [[ 83 116 118]
  [ 84 117 119]
  [ 96 113 115]
  ...
  [186 172 167]
  [194 174 164]
  [195 176 165]]

 [[ 86 121 111]
  [ 86 121 111]
  [ 95 116 113]
  ...
  [191 171 163]
  [196 175 162]
  [198 177 165]]]
[[[150 152 154]
  [153 154 156]
  [147 159 157]
  ...
  [198 175 142]
  [188 178 140]
  [190 180 143]]

 [[147 161 154]
  [149 163 156]
  [152 159 158]
  ...
  [193 177 143]
  [188 181 141]
  [188 181 141]]

 [[147 158 159]
  [148 159 160]
  [154 160 157]
  ...
  [190 177 148]
  [188 179 146]
  [188 179 146]]

 ...

 [[ 93 107 121]
  [ 94 108 122]
  [ 96 113 115]
  ..

[[[127 143 150]
  [129 145 152]
  [137 149 142]
  ...
  [178 162 135]
  [167 158 144]
  [170 162 147]]

 [[148 149 146]
  [148 149 146]
  [141 150 142]
  ...
  [174 163 135]
  [170 161 142]
  [175 165 146]]

 [[144 147 140]
  [144 147 140]
  [137 147 145]
  ...
  [172 163 137]
  [169 164 140]
  [173 167 143]]

 ...

 [[ 86 100 114]
  [ 86 100 114]
  [ 70 107 106]
  ...
  [186 148 113]
  [183 164 138]
  [188 170 143]]

 [[ 94 106  99]
  [ 92 103  97]
  [ 74 105 100]
  ...
  [178 143 112]
  [185 163 128]
  [194 172 137]]

 [[ 99 102  85]
  [ 95  98  82]
  [ 84  99  88]
  ...
  [170 148 111]
  [186 161 119]
  [197 173 131]]]
[[[132 148 134]
  [138 154 140]
  [134 156 137]
  ...
  [165 163 136]
  [186 160 130]
  [186 160 130]]

 [[129 149 137]
  [134 154 141]
  [135 153 139]
  ...
  [169 163 134]
  [180 159 133]
  [182 161 135]]

 [[139 147 144]
  [142 150 146]
  [137 150 139]
  ...
  [172 163 137]
  [175 163 140]
  [179 166 143]]

 ...

 [[ 98 116  97]
  [ 96 114  95]
  [ 67 111 102]
  ..

[[[128 138 136]
  [129 139 137]
  [138 144 132]
  ...
  [172 161 133]
  [169 160 132]
  [169 160 132]]

 [[138 137 135]
  [139 138 136]
  [139 142 132]
  ...
  [173 159 132]
  [163 165 132]
  [162 163 131]]

 [[142 148 131]
  [140 145 129]
  [136 141 135]
  ...
  [169 159 133]
  [165 163 134]
  [165 163 134]]

 ...

 [[ 63 107  97]
  [ 63 107  97]
  [ 61 109 101]
  ...
  [167 161 146]
  [165 161 146]
  [166 162 147]]

 [[ 61 102 104]
  [ 63 103 105]
  [ 59 115  99]
  ...
  [167 161 146]
  [164 163 147]
  [166 164 148]]

 [[ 60  98 108]
  [ 63 100 110]
  [ 57 116  97]
  ...
  [167 159 149]
  [165 162 144]
  [168 164 147]]]
[[[135 134 137]
  [136 135 138]
  [128 145 133]
  ...
  [179 150 136]
  [159 157 141]
  [155 154 138]]

 [[130 137 138]
  [130 137 138]
  [128 142 135]
  ...
  [168 152 139]
  [169 155 141]
  [165 152 138]]

 [[133 136 142]
  [132 135 141]
  [126 141 139]
  ...
  [169 157 138]
  [168 158 139]
  [168 158 139]]

 ...

 [[ 49 103 106]
  [ 53 107 109]
  [ 71 107 101]
  ..

In [1]:
import numpy as np 
import cv2,time,pandas

first_frame = None
status_list = [None, None]
times = []
df = pandas.DataFrame(columns= ["Start","End"])

video = cv2.VideoCapture(0)

while True:

    check, frame = video.read()
    print(frame)
    status = 0
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    gray = cv2.GaussianBlur(gray, (21, 21), 0)
    
    if first_frame is None:
        first_frame = gray
        continue
        
    delta_frame = cv2.absdiff(first_frame, gray)
    thresh_delta = cv2.threshold(delta_frame, 30, 255, cv2.THRESH_BINARY)[1]
    thresh_delta = cv2.dilate(thresh_delta, None, iterations=0 )
    cnts,hierachy=cv2.findContours(thresh_delta,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
   #(_,cnts,_) = cv2.findContours(thresh_delta.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    
    
    for contour in cnts:
        if cv2.contourArea(contour) < 1000:
            continue
        status = 1
        (x, y, w, h) = cv2.boundingReact(contour)
        cv2.reactangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 3)

    status_list.append(status)
    status_list=status_list[-2:]
    
    if status_list[-1]==1 and status_list[-2]==0:
        times.append(datetime.now())
    if status_list[-1]==0 and status_list[-2]==1:
        times.append(datetime.now())
        

    #v2.imshow("frame", frame)
    cv2.imshow("Capturing", gray)
    #cv2.imshow("delta", delta_frame)
    #cv2.imshow("thresh",thresh_delta)
       
    key = cv2.waitKey(1)
    
    if key == ord('q'):
        break
        
for i in range(0, len(times), 2):
    df=df.append(("Start:".times[i],"End:".time[i+1]), ignore_index=True )
    
df.to_csv("Times.csv")

video.release()

cv2.destroyAllWindows()

[[[110 117  91]
  [111 118  92]
  [ 74 116  95]
  ...
  [118 112  90]
  [ 92 116  92]
  [ 96 121  96]]

 [[145 110  98]
  [141 107  94]
  [ 89 110  97]
  ...
  [104 117  92]
  [ 87 121  88]
  [ 90 124  91]]

 [[107 118 114]
  [100 111 107]
  [ 87 107 104]
  ...
  [102 118  92]
  [ 96 117  88]
  [ 95 116  87]]

 ...

 [[ 82  95  82]
  [ 87 101  87]
  [100 111  71]
  ...
  [104  81  73]
  [ 79  98  61]
  [ 84 103  66]]

 [[ 78 106  77]
  [ 78 106  77]
  [104 104  76]
  ...
  [ 98  88  71]
  [ 82  95  63]
  [ 84  97  65]]

 [[101  98 101]
  [ 97  94  97]
  [107  91  77]
  ...
  [ 94 101  66]
  [ 78  90  63]
  [ 76  87  60]]]
[[[ 69 115 114]
  [ 68 114 113]
  [ 77 109 122]
  ...
  [104 105 100]
  [105  86 123]
  [108  89 126]]

 [[102 120 108]
  [ 98 116 104]
  [ 75 108 118]
  ...
  [107 101  93]
  [105  90 113]
  [105  90 113]]

 [[ 83 125  97]
  [ 82 123  96]
  [ 79 119 103]
  ...
  [103 104  88]
  [ 99 103  91]
  [ 99 103  91]]

 ...

 [[ 95  86  79]
  [100  91  83]
  [ 92  94  87]
  ..

AttributeError: module 'cv2.cv2' has no attribute 'boundingReact'